spanbert_base:
  bert_config_file: gs://xiaoy-data/spanbert_base/config.json
  dropout_rate: 0.3
  span_ratio: 0.2
  max_candidate_num: 30
  max_antecedent_num: 20
  max_span_width: 10
  sliding_window_size: 128
  pad_idx: -4
  use_span_width_embeddings: false
  span_width_embed_size: 1024 
  ffnn_size: 1024
  ffnn_depth: 1
  mention_start_idx: 37
  mention_end_idx: 42
  speaker_start_idx: 19
  speaker_end_idx: 73
  max_question_len: 128

  num_epochs: 10
  num_docs: 2802
  save_checkpoints_steps: 500
  init_checkpoint: gs://xiaoy-data/spanbert_base/pytorch_model.bin
  train_file: gs://xiaoy-data/data/train.english.tfrecord

  bert_init_lr: 0.00001
  task_init_lr: 0.00001
  bert_opt: adam_weight_decay
  task_opt: adam_weight_decay
  freeze: -1
  warmup_ratio: 0.1

spanbert_large:
  bert_config_file: gs://xiaoy-data/spanbert_large/config.json
  dropout_rate: 0.3
  span_ratio: 0.2
  max_candidate_num: 30
  max_antecedent_num: 20
  max_span_width: 10
  sliding_window_size: 128
  pad_idx: -4
  use_span_width_embeddings: false
  span_width_embed_size: 1024 
  ffnn_size: 1024
  ffnn_depth: 1
  mention_start_idx: 37
  mention_end_idx: 42
  speaker_start_idx: 19
  speaker_end_idx: 73
  max_question_len: 128

  num_epochs: 10
  num_docs: 2802
  save_checkpoints_steps: 500
  init_checkpoint: gs://xiaoy-data/spanbert_large/pytorch_model.bin
  train_file: gs://xiaoy-data/data/train.english.tfrecord

  bert_init_lr: 0.00001
  task_init_lr: 0.00001
  bert_opt: adam_weight_decay
  task_opt: adam_weight_decay
  freeze: -1
  warmup_ratio: 0.1